### ISSUE TITLE
any bag with tags loaded as film bag

### ISSUE THREAD

**Issue by bturkus** [NYPL/ami-tools#40]
pretty self explanatory

**Comment by nkrabben** [comment]
The issue was that I use a non-exclusive set comparison to figure out what kind of bag it is based on the folders in `data`. It has to be non-exclusive because `Images` isn't required.
https://github.com/NYPL/ami-tools/blob/c5732930ac92951b91e6e1e05be76ffab20eec8b/ami_bag/ami_bag.py#L344
https://github.com/NYPL/ami-tools/blob/c5732930ac92951b91e6e1e05be76ffab20eec8b/ami_bag/ami_bag.py#L382
https://github.com/NYPL/ami-tools/blob/c5732930ac92951b91e6e1e05be76ffab20eec8b/ami_bag/ami_bag_constants.py#L50

Because film bags look exactly like Video bags but with a mezz folder, the algo would loop through the types like this
video: yes, subtype = video
audio: no, subtype = video
film: yes, subtype = film

Easiest fix is to change the order in ami_bag_constants dict for subtypes, but I'm doubling down just in case and adding a mezz check to `set_json_subtype`
